return { -- this table overrides highlights in all themes
  -- Normal = { bg = "#000000" },
  -- NeoTreeGitAdded = { fg = "#50fa7b" },
  -- NeoTreeGitDeleted = { fg = "#FF5555" },
  -- NeoTreeGitModified = { fg = "#F1FA8C" },
  -- NeoTreeGitUntracked = { fg = "#FF5555" },
  -- NeoTreeGitIgnored = { fg = "#6272A4" },
  -- NeoTreeGitConflict = { fg = "#FF5555" },
  NeoTreeGitDeleted = { fg = "#FF5555" },
  NeoTreeGitModified = { fg = "#FFB86C" },
  NeoTreeGitUntracked = { fg = "#F1FA8C" },
  NeoTreeGitIgnored = { fg = "#6272A4" },
  NeoTreeGitConflict = { fg = "#FF5555" },
  NeoTreeGitAdded = { fg = "#50fa7b" },
}
